### ISSUE TITLE
ArchivesSpace v3.0 - agent-related associated_fields

### ISSUE THREAD

**Issue by djpillen** [alexduryee/timewalk#6]
I was taking ArchivesSpace v3.0 for a spin and was unable to save anything with a date subrecord. Found the following in the logs:

```
undefined method `related_agents_rlshp_id' for #<ASDate:0x523e9403>: /usr/local/archivesspace/plugins/timewalk/backend/model/ASDate.rb:34
```

ArchivesSpace v3.0 replaces standard date subrecords on agents with "structured dates" and drops agent-related FKs from the date table: https://github.com/archivesspace/archivesspace/blob/master/common/db/migrations/143_migrate_agent_date_data_to_structured_dates.rb#L58

I ran a quick test again after getting rid of the agent-related FKs from the associated_fields array and everything seemed to be working again: https://github.com/alexduryee/timewalk/blob/master/backend/model/ASDate.rb#L17-L25

Not sure how you'd like to handle version-specific differences like this, but just wanted to give a heads up.

**Comment by Blake-** [comment]
Seeing the same thing here trying to run on 3.0.1:

"error": "undefined method `related_agents_rlshp_id' for #<ASDate:0x6ac057d7>: /archivesspace/plugins/timewalk/backend/model/ASDate.rb:34:in `block in populate'\n\torg/jruby/RubyArray.java:1809:in `each'\n\t/archivesspace/plugins/timewalk/backend/model/ASDate.rb:33:in `populate'\n\t/archivesspace/plugins/timewalk/backend/model/ASDate.rb:64:in `around_save'\n\t/archivesspace/gems/gems/sequel-5.9.0/lib/sequel/model/base.rb:1717:in `_save'\n\t/archivesspace/gems/gems/sequel-5.9.0/lib/sequel/model/base.rb:1446:in `block in save'\n\t/archivesspace/gems/gems/sequel-5.9.0/lib/sequel/model/base.rb:1864:in `block in checked_transaction'\n\t/archivesspace/gems/gems/sequel-5.9.0/lib/sequel/database/transactions.rb:175:in `block in transaction'\n\t/archivesspace/gems/gems/sequel-5.9.0/lib/sequel/connection_pool/threaded.rb:87:in `hold'\n\t/archivesspace/gems/gems/sequel-5.9.0/lib/sequel/database/connecting.rb:270:in `synchronize'\n\t/archivesspace/gems/gems/sequel-5.9.0/lib/sequel/database/transactions.rb:145:in `transaction'\n\t/archivesspace/gems/gems/sequel-5.9.0/lib/sequel/model/base.rb:1864:in `checked_transaction'\n\t/archivesspace/gems/gems/sequel-5.9.0/lib/sequel/model/base.rb:1446:in `block in save'\n\t/archivesspace/gems/gems/sequel-5.9.0/lib/sequel/model/base.rb:1852:in `checked_save_failure'\n\t/archivesspace/gems/gems/sequel-5.9.0/lib/sequel/model/base.rb:1446:in `save'\n\t/archivesspace/gems/gems/sequel-5.9.0/lib/sequel/model/base.rb:254:in `create'\n\t/archivesspace/data/tmp/jetty-0.0.0.0-8089-backend.war-_-any-/webapp/WEB-INF/app/model/ASModel_crud.rb:363:in `create_from_json'\n\t/archivesspace/data/tmp/jetty-0.0.0.0-8089-backend.war-_-any-/webapp/WEB-INF/app/model/mixins/relationships.rb:867:in `create_from_json'\n\t/archivesspace/data/tmp/jetty-0.0.0.0-8089-backend.war-_-any-/webapp/WEB-INF/app/model/ASModel_crud.rb:120:in `block in apply_nested_records'\n\torg/jruby/RubyArray.java:1809:in `each'\n\torg/jruby/RubyEnumerable.java:1258:in `each_with_index'\n\t/archivesspace/data/tmp/jetty-0.0.0.0-8089-backend.war-_-any-/webapp/WEB-INF/app/model/ASModel_crud.rb:85:in `block in apply_nested_records'\n\torg/jruby/RubyArray.java:1809:in `each'\n\t/archivesspace/data/tmp/jetty-0.0.0.0-8089-backend.war-_-any-/webapp/WEB-INF/app/model/ASModel_crud.rb:63:in `apply_nested_records'\n\t/archivesspace/data/tmp/jetty-0.0.0.0-8089-backend.war-_-any-/webapp/WEB-INF/app/model/ASModel_crud.rb:366:in `create_from_json'\n\t/archivesspace/data/tmp/jetty-0.0.0.0-8089-backend.war-_-any-/webapp/WEB-INF/app/model/mixins/relationships.rb:867:in `create_from_json'\n\t/archivesspace/data/tmp/jetty-0.0.0.0-8089-backend.war-_-any-/webapp/WEB-INF/app/model/mixins/notes.rb:152:in `create_from_json'\n\t/archivesspace/data/tmp/jetty-0.0.0.0-8089-backend.war-_-any-/webapp/WEB-INF/app/model/mixins/auto_generator.rb:39:in `create_from_json'\n\t/archivesspace/data/tmp/jetty-0.0.0.0-8089-backend.war-_-any-/webapp/WEB-INF/app/model/mixins/publishable.rb:23:in `create_from_json'\n\t/archivesspace/data/tmp/jetty-0.0.0.0-8089-backend.war-_-any-/webapp/WEB-INF/app/model/mixins/rights_restriction_notes.rb:23:in `create_from_json'\n\t/archivesspace/data/tmp/jetty-0.0.0.0-8089-backend.war-_-any-/webapp/WEB-INF/app/model/resource.rb:76:in `create_from_json'\n\t/archivesspace/data/tmp/jetty-0.0.0.0-8089-backend.war-_-any-/webapp/WEB-INF/app/lib/crud_helpers.rb:11:in `handle_create'\n\t/archivesspace/data/tmp/jetty-0.0.0.0-8089-backend.war-_-any-/webapp/WEB-INF/app/controllers/resource.rb:13:in `block in ArchivesSpaceService'\n\torg/jruby/RubyBasicObject.java:2622:in `instance_eval'\n\t/archivesspace/data/tmp/jetty-0.0.0.0-8089-backend.war-_-any-/webapp/WEB-INF/app/lib/rest.rb:378:in `block in returns'\n\t/archivesspace/data/tmp/jetty-0.0.0.0-8089-backend.war-_-any-/webapp/WEB-INF/app/model/db.rb:198:in `block in open'\n\t/archivesspace/data/tmp/jetty-0.0.0.0-8089-backend.war-_-any-/webapp/WEB-INF/app/model/db.rb:89:in `block in transaction'\n\t/archivesspace/gems/gems/sequel-5.9.0/lib/sequel/database/transactions.rb:204:in `_transaction'\n\t/archivesspace/gems/gems/sequel-5.9.0/lib/sequel/database/transactions.rb:179:in `block in transaction'\n\t/archivesspace/gems/gems/sequel-5.9.0/lib/sequel/connection_pool/threaded.rb:91:in `hold'\n\t/archivesspace/gems/gems/sequel-5.9.0/lib/sequel/database/connecting.rb:270:in `synchronize'\n\t/archivesspace/gems/gems/sequel-5.9.0/lib/sequel/database/transactions.rb:145:in `transaction'\n\t/archivesspace/data/tmp/jetty-0.0.0.0-8089-backend.war-_-any-/webapp/WEB-INF/app/model/db.rb:88:in `transaction'\n\t/archivesspace/data/tmp/jetty-0.0.0.0-8089-backend.war-_-any-/webapp/WEB-INF/app/model/db.rb:195:in `block in open'\n\t/archivesspace/data/tmp/jetty-0.0.0.0-8089-backend.war-_-any-/webapp/WEB-INF/app/model/db.rb:192:in `open'\n\t/archivesspace/data/tmp/jetty-0.0.0.0-8089-backend.war-_-any-/webapp/WEB-INF/app/model/db.rb:520:in `block in DB'\n\t/archivesspace/data/tmp/jetty-0.0.0.0-8089-backend.war-_-any-/webapp/WEB-INF/app/lib/rest.rb:361:in `block in returns'\n\t/archivesspace/data/tmp/jetty-0.0.0.0-8089-backend.war-_-any-/webapp/WEB-INF/app/lib/request_context.rb:24:in `open'\n\t/archivesspace/data/tmp/jetty-0.0.0.0-8089-backend.war-_-any-/webapp/WEB-INF/app/lib/rest.rb:329:in `block in returns'\n\torg/jruby/RubyMethod.java:115:in `call'\n\t/archivesspace/gems/gems/sinatra-2.0.5/lib/sinatra/base.rb:1635:in `block in compile!'\n\t/archivesspace/gems/gems/sinatra-2.0.5/lib/sinatra/base.rb:992:in `block in route!'\n\t/archivesspace/gems/gems/sinatra-2.0.5/lib/sinatra/base.rb:1011:in `route_eval'\n\t/archivesspace/gems/gems/sinatra-2.0.5/lib/sinatra/base.rb:992:in `block in route!'\n\t/archivesspace/gems/gems/sinatra-2.0.5/lib/sinatra/base.rb:1040:in `block in process_route'\n\torg/jruby/RubyKernel.java:1189:in `catch'\n\t/archivesspace/gems/gems/sinatra-2.0.5/lib/sinatra/base.rb:1038:in `process_route'\n\t/archivesspace/gems/gems/sinatra-2.0.5/lib/sinatra/base.rb:990:in `block in route!'\n\torg/jruby/RubyArray.java:1809:in `each'\n\t/archivesspace/gems/gems/sinatra-2.0.5/lib/sinatra/base.rb:989:in `route!'\n\t/archivesspace/gems/gems/sinatra-2.0.5/lib/sinatra/base.rb:1097:in `block in dispatch!'\n\t/archivesspace/gems/gems/sinatra-2.0.5/lib/sinatra/base.rb:1076:in `block in invoke'\n\torg/jruby/RubyKernel.java:1189:in `catch'\n\t/archivesspace/gems/gems/sinatra-2.0.5/lib/sinatra/base.rb:1076:in `invoke'\n\t/archivesspace/gems/gems/sinatra-2.0.5/lib/sinatra/base.rb:1094:in `dispatch!'\n\t/archivesspace/gems/gems/sinatra-2.0.5/lib/sinatra/base.rb:924:in `block in call!'\n\t/archivesspace/gems/gems/sinatra-2.0.5/lib/sinatra/base.rb:1076:in `block in invoke'\n\torg/jruby/RubyKernel.java:1189:in `catch'\n\t/archivesspace/gems/gems/sinatra-2.0.5/lib/sinatra/base.rb:1076:in `invoke'\n\t/archivesspace/gems/gems/sinatra-2.0.5/lib/sinatra/base.rb:924:in `call!'\n\t/archivesspace/gems/gems/sinatra-2.0.5/lib/sinatra/base.rb:913:in `call'\n\t/archivesspace/data/tmp/jetty-0.0.0.0-8089-backend.war-_-any-/webapp/WEB-INF/app/main.rb:302:in `call'\n\t/archivesspace/gems/gems/rack-protection-2.0.5/lib/rack/protection/xss_header.rb:18:in `call'\n\t/archivesspace/gems/gems/rack-protection-2.0.5/lib/rack/protection/path_traversal.rb:16:in `call'\n\t/archivesspace/gems/gems/rack-protection-2.0.5/lib/rack/protection/json_csrf.rb:26:in `call'\n\t/archivesspace/gems/gems/rack-protection-2.0.5/lib/rack/protection/base.rb:50:in `call'\n\t/archivesspace/gems/gems/rack-protection-2.0.5/lib/rack/protection/base.rb:50:in `call'\n\t/archivesspace/gems/gems/rack-protection-2.0.5/lib/rack/protection/frame_options.rb:31:in `call'\n\turi:classloader:/vendor/rack-2.2.3/rack/null_logger.rb:11:in `call'\n\turi:classloader:/vendor/rack-2.2.3/rack/head.rb:12:in `call'\n\t/archivesspace/gems/gems/sinatra-2.0.5/lib/sinatra/base.rb:194:in `call'\n\t/archivesspace/gems/gems/sinatra-2.0.5/lib/sinatra/base.rb:1957:in `call'\n\t/archivesspace/gems/gems/sinatra-2.0.5/lib/sinatra/base.rb:1502:in `block in call'\n\t/archivesspace/gems/gems/sinatra-2.0.5/lib/sinatra/base.rb:1729:in `synchronize'\n\t/archivesspace/gems/gems/sinatra-2.0.5/lib/sinatra/base.rb:1502:in `call'\n\turi:classloader:/vendor/rack-2.2.3/rack/urlmap.rb:74:in `block in call'\n\torg/jruby/RubyArray.java:1809:in `each'\n\turi:classloader:/vendor/rack-2.2.3/rack/urlmap.rb:58:in `call'\n\turi:classloader:/rack/handler/servlet.rb:22:in `call'"

**Comment by mdemers** [comment]
I think we're having similar problems on 3.0.2. Our team was unable to save an records using dates and we've been forced to disable the plugin. 

D, [2021-10-04T12:43:09.686647 #2455] DEBUG -- : Thread-3006: Responded with [500, {"Content-Type"=>"application/json", "Cache-Control"=>"private, must-revalidate, max-age=0", "Content-Length"=>"9222"}, ["{\"error\":\"undefined method `related_agents_rlshp_id' for #<ASDate:0x7c01079f>: /var/www/archivesspace/plugins/timewalk/backend/model/ASDate.rb:34:in `block in populate'\\n\\torg/jruby/RubyArray.java:1809:in `each'\\n\\t/var/www/archivesspace/plugins/timewalk/backend/model/ASDate.rb:33:in `populate'\\n\\t/var/www/archivesspace/plugins/timewalk/backend/model/ASDate.rb:64:in `around... in 566ms
F, [2021-10-04T12:43:09.718679 #2455] FATAL -- :
F, [2021-10-04T12:43:09.722542 #2455] FATAL -- : Exception (Unknown response: {"error":"undefined method `related_agents_rlshp_id' for #<ASDate:0x7c01079f>: /var/www/archivesspace/plugins/timewalk/backend/model/ASDate.rb:34:in `block in populate'\n\torg/jruby/RubyArray.java:1809:in `each'\n\t/var/www/archivesspace/plugins/timewalk/backend/model/ASDate.rb:33:in `populate'\n\t/var/www/archivesspace/plugins/timewalk/backend/model/ASDate.rb:64:in `around_save'\n\t/var/www/archivesspace/gems/gems/sequel-5.9.0/lib/sequel/model/base.rb:1717:in `_save'\n\t/var/www/archivesspace/gems/gems/sequel-5.9.0/lib/sequel/model/base.rb:1446:in `block in save'\n\t/var/www/archivesspace/gems/gems/sequel-5.9.0/lib/sequel/model/base.rb:1864:in `block in checked_transaction'\n\t/var/www/archivesspace/gems/gems/sequel-5.9.0/lib/sequel/database/transactions.rb:175:in `block in transaction'\n\t/var/www/archivesspace/gems/gems/sequel-5.9.0/lib/sequel/connection_pool/threaded.rb:87:in `hold'\n\t/var/www/archivesspace/gems/gems/sequel-5.9.0/lib/sequel/database/connecting.rb:270:in `synchronize'\n\t/var/www/archivesspace/gems/gems/sequel-5.9.0/lib/sequel/database/transactions.rb:145:in `transaction'\n\t/var/www/archivesspace/gems/gems/sequel-5.9.0/lib/sequel/model/base.rb:1864:in `checked_transaction'\n\t/var/www/archivesspace/gems/gems/sequel-5.9.0/lib/sequel/model/base.rb:1446:in `block in save'\n\t/var/www/archivesspace/gems/gems/sequel-5.9.0/lib/sequel/model/base.rb:1852:in `checked_save_failure'\n\t/var/www/archivesspace/gems/gems/sequel-5.9.0/lib/sequel/model/base.rb:1446:in `save'\n\t/var/www/archivesspace/gems/gems/sequel-5.9.0/lib/sequel/model/base.rb:254:in `create'\n\t/var/www/archivesspace/data/tmp/jetty-0.0.0.0-8089-backend.war-_-any-/webapp/WEB-INF/app/model/ASModel_crud.rb:363:in `create_from_json'\n\t/var/www/archivesspace/data/tmp/jetty-0.0.0.0-8089-backend.war-_-any-/webapp/WEB-INF/app/model/mixins/relationships.rb:867:in `create_from_json'\n\t/var/www/archivesspace/data/tmp/jetty-0.0.0.0-8089-backend.war-_-any-/webapp/WEB-INF/app/model/ASModel_crud.rb:120:in `block in apply_nested_records'\n\torg/jruby/RubyArray.java:1809:in `each'\n\torg/jruby/RubyEnumerable.java:1258:in `each_with_index'\n\t/var/www/archivesspace/data/tmp/jetty-0.0.0.0-8089-backend.war-_-any-/webapp/WEB-INF/app/model/ASModel_crud.rb:85:in `block in apply_nested_records'\n\torg/jruby/RubyArray.java:1809:in `each'\n\t/var/www/archivesspace/data/tmp/jetty-0.0.0.0-8089-backend.war-_-any-/webapp/WEB-INF/app/model/ASModel_crud.rb:63:in `apply_nested_records'\n\t/var/www/archivesspace/data/tmp/jetty-0.0.0.0-8089-backend.war-_-any-/webapp/WEB-INF/app/model/ASModel_crud.rb:213:in `update_from_json'\n\t/var/www/archivesspace/data/tmp/jetty-0.0.0.0-8089-backend.war-_-any-/webapp/WEB-INF/app/model/mixins/relationships.rb:514:in `update_from_json'\n\t/var/www/archivesspace/data/tmp/jetty-0.0.0.0-8089-backend.war-_-any-/webapp/WEB-INF/app/model/mixins/trees.rb:290:in `update_from_json'\n\t/var/www/archivesspace/data/tmp/jetty-0.0.0.0-8089-backend.war-_-any-/webapp/WEB-INF/app/model/mixins/notes.rb:17:in `update_from_json'\n\t/var/www/archivesspace/data/tmp/jetty-0.0.0.0-8089-backend.war-_-any-/webapp/WEB-INF/app/model/mixins/auto_generator.rb:23:in `update_from_json'\n\t/var/www/archivesspace/data/tmp/jetty-0.0.0.0-8089-backend.war-_-any-/webapp/WEB-INF/app/model/mixins/reindex_top_containers.rb:96:in `update_from_json'\n\t/var/www/archivesspace/data/tmp/jetty-0.0.0.0-8089-backend.war-_-any-/webapp/WEB-INF/app/model/mixins/rights_restriction_notes.rb:14:in `update_from_json'\n\t/var/www/archivesspace/data/tmp/jetty-0.0.0.0-8089-backend.war-_-any-/webapp/WEB-INF/app/model/resource.rb:89:in `update_from_json'\n\t/var/www/archivesspace/data/tmp/jetty-0.0.0.0-8089-backend.war-_-any-/webapp/WEB-INF/app/lib/crud_helpers.rb:5:in `handle_update'\n\t/var/www/archivesspace/data/tmp/jetty-0.0.0.0-8089-backend.war-_-any-/webapp/WEB-INF/app/controllers/resource.rb:123:in `block in ArchivesSpaceService'\n\torg/jruby/RubyBasicObject.java:2622:in `instance_eval'\n\t/var/www/archivesspace/data/tmp/jetty-0.0.0.0-8089-backend.war-_-any-/webapp/WEB-INF/app/lib/rest.rb:378:in `block in returns'\n\t/var/www/archivesspace/data/tmp/jetty-0.0.0.0-8089-backend.war-_-any-/webapp/WEB-INF/app/model/db.rb:198:in `block in open'\n\t/var/www/archivesspace/data/tmp/jetty-0.0.0.0-8089-backend.war-_-any-/webapp/WEB-INF/app/model/db.rb:89:in `block in transaction'\n\t/var/www/archivesspace/gems/gems/sequel-5.9.0/lib/sequel/database/transactions.rb:204:in `_transaction'\n\t/var/www/archivesspace/gems/gems/sequel-5.9.0/lib/sequel/database/transactions.rb:179:in `block in transaction'\n\t/var/www/archivesspace/gems/gems/sequel-5.9.0/lib/sequel/connection_pool/threaded.rb:91:in `hold'\n\t/var/www/archivesspace/gems/gems/sequel-5.9.0/lib/sequel/database/connecting.rb:270:in `synchronize'\n\t/var/www/archivesspace/gems/gems/sequel-5.9.0/lib/sequel/database/transactions.rb:145:in `transaction'\n\t/var/www/archivesspace/data/tmp/jetty-0.0.0.0-8089-backend.war-_-any-/webapp/WEB-INF/app/model/db.rb:88:in `transaction'\n\t/var/www/archivesspace/data/tmp/jetty-0.0.0.0-8089-backend.war-_-any-/webapp/WEB-INF/app/model/db.rb:195:in `block in open'\n\t/var/www/archivesspace/data/tmp/jetty-0.0.0.0-8089-backend.war-_-any-/webapp/WEB-INF/app/model/db.rb:192:in `open'\n\t/var/www/archivesspace/data/tmp/jetty-0.0.0.0-8089-backend.war-_-any-/webapp/WEB-INF/app/model/db.rb:520:in `block in DB'\n\t/var/www/archivesspace/data/tmp/jetty-0.0.0.0-8089-backend.war-_-any-/webapp/WEB-INF/app/lib/rest.rb:361:in `block in returns'\n\t/var/www/archivesspace/data/tmp/jetty-0.0.0.0-8089-backend.war-_-any-/webapp/WEB-INF/app/lib/request_context.rb:24:in `open'\n\t/var/www/archivesspace/data/tmp/jetty-0.0.0.0-8089-backend.war-_-any-/webapp/WEB-INF/app/lib/rest.rb:329:in `block in returns'\n\torg/jruby/RubyMethod.java:115:in `call'\n\t/var/www/archivesspace/gems/gems/sinatra-2.0.5/lib/sinatra/base.rb:1635:in `block in compile!'\n\t/var/www/archivesspace/gems/gems/sinatra-2.0.5/lib/sinatra/base.rb:992:in `block in route!'\n\t/var/www/archivesspace/gems/gems/sinatra-2.0.5/lib/sinatra/base.rb:1011:in `route_eval'\n\t/var/www/archivesspace/gems/gems/sinatra-2.0.5/lib/sinatra/base.rb:992:in `block in route!'\n\t/var/www/archivesspace/gems/gems/sinatra-2.0.5/lib/sinatra/base.rb:1040:in `block in process_route'\n\torg/jruby/RubyKernel.java:1189:in `catch'\n\t/var/www/archivesspace/gems/gems/sinatra-2.0.5/lib/sinatra/base.rb:1038:in `process_route'\n\t/var/www/archivesspace/gems/gems/sinatra-2.0.5/lib/sinatra/base.rb:990:in `block in route!'\n\torg/jruby/RubyArray.java:1809:in `each'\n\t/var/www/archivesspace/gems/gems/sinatra-2.0.5/lib/sinatra/base.rb:989:in `route!'\n\t/var/www/archivesspace/gems/gems/sinatra-2.0.5/lib/sinatra/base.rb:1097:in `block in dispatch!'\n\t/var/www/archivesspace/gems/gems/sinatra-2.0.5/lib/sinatra/base.rb:1076:in `block in invoke'\n\torg/jruby/RubyKernel.java:1189:in `catch'\n\t/var/www/archivesspace/gems/gems/sinatra-2.0.5/lib/sinatra/base.rb:1076:in `invoke'\n\t/var/www/archivesspace/gems/gems/sinatra-2.0.5/lib/sinatra/base.rb:1094:in `dispatch!'\n\t/var/www/archivesspace/gems/gems/sinatra-2.0.5/lib/sinatra/base.rb:924:in `block in call!'\n\t/var/www/archivesspace/gems/gems/sinatra-2.0.5/lib/sinatra/base.rb:1076:in `block in invoke'\n\torg/jruby/RubyKernel.java:1189:in `catch'\n\t/var/www/archivesspace/gems/gems/sinatra-2.0.5/lib/sinatra/base.rb:1076:in `invoke'\n\t/var/www/archivesspace/gems/gems/sinatra-2.0.5/lib/sinatra/base.rb:924:in `call!'\n\t/var/www/archivesspace/gems/gems/sinatra-2.0.5/lib/sinatra/base.rb:913:in `call'\n\t/var/www/archivesspace/data/tmp/jetty-0.0.0.0-8089-backend.war-_-any-/webapp/WEB-INF/app/main.rb:302:in `call'\n\t/var/www/archivesspace/plugins/as-cors/backend/plugin_init.rb:32:in `call'\n\t/var/www/archivesspace/gems/gems/rack-protection-2.0.5/lib/rack/protection/

**Comment by alexduryee** [comment]
Resolved in #7.  Apologies for taking so long to see this thread!

**Comment by mdemers** [comment]
Just saw you had added new commits. My comment on the issue with the error log doesn't reflect your new code, sorry! We will test the new release soon, thank you!!!
